### ISSUE TITLE
昨天代码跑tensorflow2ncnn报：libprotobuf FATAL /protobuf_install/include/google/protobuf/repeated_field.h:1184] CHECK failed: (index) < (current_size_)

### ISSUE THREAD

**Issue by dpars7** [Tencent/ncnn#163] opened 2017-10-19 02:28 UTC
更新昨天代码，用tensorflow2ncnn跑Resnet.pb，报下面的错误：
[libprotobuf FATAL protobuf_install/include/google/protobuf/repeated_field.h:1184] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
Aborted (core dumped)

跟进发现是node.op() == "Maximum"时没有插入“MemoryData”所致；
后面增加下面的代码就没报错（9月20多号是默认这个为true）：
                if (node.op() == "Maximum")
                    isBinaryOp = true;

**Comment by FishermanZzhang** [comment] 2017-11-15 02:49
我也碰到了这个问题， 

Abs not supported yet !
nT #1
Sign not supported yet !
nT #1
Cast not supported yet !
nSrcT #1
DstT #3
Transpose not supported yet !
nT #1
Tperm #3
Shape not supported yet !
nT #1
out_type #3
StridedSlice not supported yet !
nnew_axis_mask #0
end_mask #0
T #3
.....
[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1522] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
已放弃 (核心已转储)


什么时候有结果方案 @nihui

**Comment by nihui** [comment] 2018-12-18 03:11
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:11 UTC
Labels: tensorflow do not like ncnn

**Comment by YUHAO19910716** [comment] 2018-12-26 10:01
metoo.
i get this error\:who can help me
[libprotobuf FATAL /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/externals/protobuf/x86_64/10.0/include/google/protobuf/repeated_field.h:1408] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google_private::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
Aborted (core dumped)
