### ISSUE TITLE
tensorflow2ncnn 报错

### ISSUE THREAD

**Issue by double-vane** [Tencent/ncnn#450] opened 2018-06-22 08:08 UTC
tensorflow2ncnn编译成功，但是在使用的时候，出现错误，请教这个问题怎么解决？
:~/ncnn/ncnn/build/tools/tensorflow$ ./tensorflow2ncnn idcard.pb
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)

**Comment by nihui** [comment] 2018-12-18 03:12
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:12 UTC
Labels: tensorflow do not like ncnn
