### ISSUE TITLE
TX2平台上调用libncnn.a出现的问题

### ISSUE THREAD

**Issue by emailxuchen** [Tencent/ncnn#1099] opened 2019-07-11 14:55 UTC
libncnn.a中使用了Vulkan，编译ncnn能够成功生成libncnn.a，但在应用程序中调用的时候出现如下问题：
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::~VulkanDevice()':
gpu.cpp:(.text+0xfc): undefined reference to `vkDestroyShaderModule'
gpu.cpp:(.text+0x120): undefined reference to `vkDestroyDevice'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::destroy_gpu_instance()':
gpu.cpp:(.text+0x1f4): undefined reference to `vkDestroyInstance'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::compile_shader_module(unsigned int const*, unsigned long) const':
gpu.cpp:(.text+0x2d4): undefined reference to `vkCreateShaderModule'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::destroy_shader_module()':
gpu.cpp:(.text+0x834): undefined reference to `vkDestroyShaderModule'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::init_device_extension()':
gpu.cpp:(.text+0x8a0): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x8c4): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x8d8): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x8ec): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x90c): undefined reference to `vkGetDeviceProcAddr'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o):gpu.cpp:(.text+0x920): more undefined references to `vkGetDeviceProcAddr' follow
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::create_gpu_instance()':
gpu.cpp:(.text+0x9b0): undefined reference to `vkEnumerateInstanceExtensionProperties'
gpu.cpp:(.text+0xa14): undefined reference to `vkEnumerateInstanceExtensionProperties'
gpu.cpp:(.text+0xb20): undefined reference to `vkCreateInstance'
gpu.cpp:(.text+0xbbc): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xbd0): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xbe4): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xbf8): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xc0c): undefined reference to `vkGetInstanceProcAddr'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o):gpu.cpp:(.text+0xc20): more undefined references to `vkGetInstanceProcAddr' follow
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::create_gpu_instance()':
gpu.cpp:(.text+0xc58): undefined reference to `vkEnumeratePhysicalDevices'
gpu.cpp:(.text+0xca4): undefined reference to `vkEnumeratePhysicalDevices'
gpu.cpp:(.text+0xe7c): undefined reference to `vkGetPhysicalDeviceQueueFamilyProperties'
gpu.cpp:(.text+0x1044): undefined reference to `vkGetPhysicalDeviceMemoryProperties'
gpu.cpp:(.text+0x12b8): undefined reference to `vkEnumerateDeviceExtensionProperties'
gpu.cpp:(.text+0x1320): undefined reference to `vkEnumerateDeviceExtensionProperties'
gpu.cpp:(.text+0x19ec): undefined reference to `vkGetPhysicalDeviceQueueFamilyProperties'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::create_shader_module()':
gpu.cpp:(.text+0x1dbc): undefined reference to `vkCreateShaderModule'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::VulkanDevice(int)':
gpu.cpp:(.text+0x236c): undefined reference to `vkCreateDevice'
gpu.cpp:(.text+0x2420): undefined reference to `vkGetDeviceQueue'
gpu.cpp:(.text+0x24c4): undefined reference to `vkGetDeviceQueue'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(allocator.cpp.o): In function `ncnn::VkWeightStagingBufferAllocator::fastFree(ncnn::VkBufferMemory*)':
allocator.cpp:(.text+0x78): undefined reference to `vkUnmapMemory'
allocator.cpp:(.text+0x8c): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0xa0): undefined reference to `vkFreeMemory'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(allocator.cpp.o): In function `ncnn::VkWeightBufferAllocator::clear()':
allocator.cpp:(.text+0x100): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0x114): undefined reference to `vkFreeMemory'
allocator.cpp:(.text+0x14c): undefined reference to `vkUnmapMemory'
allocator.cpp:(.text+0x188): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0x19c): undefined reference to `vkFreeMemory'
allocator.cpp:(.text+0x1d4): undefined reference to `vkUnmapMemory'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(allocator.cpp.o): In function `ncnn::VkStagingBufferAllocator::clear()':
allocator.cpp:(.text+0x28c): undefined reference to `vkUnmapMemory'
allocator.cpp:(.text+0x2a0): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0x2b4): undefined reference to `vkFreeMemory'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(allocator.cpp.o): In function `ncnn::VkBlobBufferAllocator::clear()':
allocator.cpp:(.text+0x350): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0x364): undefined reference to `vkFreeMemory'
allocator.cpp:(.text+0x39c): undefined reference to `vkUnmapMemory'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(allocator.cpp.o): In function `ncnn::VkStagingBufferAllocator::~VkStagingBufferAllocator()':
allocator.cpp:(.text+0xd50): undefined reference to `vkUnmapMemory'
allocator.cpp:(.text+0xd64): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0xd78): undefined reference to `vkFreeMemory'
/home/nvidia/VisionProject/3rdparty/ncnn/lib/libncnn.a(allocator.cpp.o): In function `ncnn::VkStagingBufferAllocator::~VkStagingBufferAllocator()':
allocator.cpp:(.text+0xe08): undefined reference to `vkUnmapMemory'
allocator.cpp:(.text+0xe1c): undefined reference to `vkDestroyBuffer'
allocator.cpp:(.text+0xe30): undefined reference to `vkFreeMemory'

**Comment by nihui** [comment] 2019-07-15 04:50
duplicate of https://github.com/Tencent/ncnn/issues/1104

**Closed by nihui** 2019-07-15 04:50 UTC

**Comment by zaidao2023** [comment] 2019-12-26 05:34
你好 请问问题解决了吗？如何解决的

**Comment by damvantai** [comment] 2021-06-24 10:23
miss library vulkan, you can add -lvulkan in target_link_libraries
