### ISSUE TITLE
ncnn output on converted from tensorflow pb wrong result

### ISSUE THREAD

**Issue by dimitryn** [Tencent/ncnn#611] opened 2018-10-16 07:15 UTC
Hi , 
I am testing several IE for the performance.
My tensorflow pb file contain 2 types of layers DepthWiseConv2D and Conv2D.
Tensorflow Lite , Mace XiaoMi , Arm nn sdk produce exactly same output.
Ncnn output completely different from all others.
Is look's like channels separated on output os need some kind of post-processing or pre-processing?
Thanks.

Uploaded source pb file and converted ncnn files
[IE_DATA.zip](https://github.com/Tencent/ncnn/files/2481834/IE_DATA.zip)

**Comment by dimitryn** [comment] 2018-10-16 08:16
Hi @nihui , so it bug ? what that mean tensorflow do not like ncnn ?

**Comment by nihui** [comment] 2018-12-18 03:13
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:13 UTC
Labels: tensorflow do not like ncnn

**Comment by tejas35** [comment] 2019-06-12 07:44
How would you convert from .pb to ncnn files ?

**Comment by dimitryn** [comment] 2019-06-12 10:56
@tejas35 as I see tensorflow not supported any more
