### ISSUE TITLE
FusedBatchNorm not supported yet !

### ISSUE THREAD

**Issue by iChiaGuo** [Tencent/ncnn#490] opened 2018-07-25 07:48 UTC
FusedBatchNorm not supported yet !
这个层如何自定义？

**Comment by lzx1413** [comment] 2018-07-25 07:50
可参考wiki

**Comment by iChiaGuo** [comment] 2018-07-26 07:46
@lzx1413 他的实现和batchnorm有什么区别，我看[这里](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/fused-batch-norm)和[这个](https://stackoverflow.com/questions/43999951/difference-between-tf-nn-batch-normalization-and-tf-nn-fused-batch-norm)，好像没有什么区别，我用batchnorm来代替加载模型出错

**Comment by nihui** [comment] 2018-12-18 03:12
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:12 UTC
Labels: tensorflow do not like ncnn
