### ISSUE TITLE
使用tensorflow2ncnn 转换模型 提示有些层还不支持

### ISSUE THREAD

**Issue by yjcn** [Tencent/ncnn#288] opened 2018-03-09 12:09 UTC
Transpose not supported yet !
Shape not supported yet !
StridedSlice not supported yet !
Pack not supported yet !

![image](https://user-images.githubusercontent.com/8858803/37206949-a652cd38-23d5-11e8-8426-dc41d050fd6e.png)

**Comment by WenguoLi** [comment] 2018-03-14 04:49
tensorflow2ncnn这个可执行文件是怎么编译出来的？ 我这边一直编译都不通过。
请问需要怎么配置才能编译通过？ 多谢

**Comment by mydear33000** [comment] 2018-04-28 02:37
Same question!
TensorArrayWriteV3 not supported yet !
nT #3
NextIteration not supported yet !
nT #1
Shape not supported yet !
nT #1
out_type #3
StridedSlice not supported yet !
nIndex #3
T #3
shrink_axis_mask #0
begin_mask #0
ellipsis_mask #0
new_axis_mask #0
end_mask #0
Greater not supported yet !
nT #3
Switch not supported yet !
nT #1
Shape not supported yet !

**Comment by nihui** [comment] 2018-12-18 03:11
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:11 UTC
Labels: tensorflow do not like ncnn

**Comment by hdwf02** [comment] 2019-04-15 02:50
> duplicate of #5

大佬 什么意思你呢 我也碰到这个问题。注掉tools不是不能生成转换工具了么
