### ISSUE TITLE
tensorflow2ncnn Slice not supported yet !

### ISSUE THREAD

**Issue by grainw** [Tencent/ncnn#614] opened 2018-10-19 08:21 UTC
在多任务学习中，将tensorflow 模型转为ncnn ，Pack not supported yet ! ，Slice not supported yet !有没有解决方案的？谢谢@nihui

**Comment by nihui** [comment] 2018-12-18 03:13
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:13 UTC
Labels: tensorflow do not like ncnn
