### ISSUE TITLE
tensorflow to ncnn not supported yet 

### ISSUE THREAD

**Issue by onexuan** [Tencent/ncnn#608] opened 2018-10-15 10:51 UTC
Relu6 not supported yet !
n_output_shapes #0
T #1
FusedBatchNorm not supported yet !
nT #1
is_training #0
epsilon #0
_output_shapes #0
data_format #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
nT #1
_output_shapes #0
FusedBatchNorm not supported yet !
nis_training #0
epsilon #0
_output_shapes #0
data_format #0
T #1
Relu6 not supported yet !
nT #1
_output_shapes #0
Relu6 not supported yet !
n_output_shapes #0
T #1
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
nT #1
_output_shapes #0
FusedBatchNorm not supported yet !
nis_training #0
epsilon #0
_output_shapes #0
data_format #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
nT #1
_output_shapes #0
FusedBatchNorm not supported yet !
nis_training #0
epsilon #0
_output_shapes #0
data_format #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nTblock_shape #3
_output_shapes #0
Tpaddings #3
T #1
BatchToSpaceND not supported yet !
nT #1
Tcrops #3
_output_shapes #0
Tblock_shape #3
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nTblock_shape #3
_output_shapes #0
Tpaddings #3
T #1
BatchToSpaceND not supported yet !
nTblock_shape #3
Tcrops #3
_output_shapes #0
T #1
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
nT #1
_output_shapes #0
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nT #1
Tblock_shape #3
_output_shapes #0
Tpaddings #3
BatchToSpaceND not supported yet !
nT #1
Tcrops #3
_output_shapes #0
Tblock_shape #3
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
nT #1
_output_shapes #0
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nTblock_shape #3
_output_shapes #0
Tpaddings #3
T #1
BatchToSpaceND not supported yet !
nTblock_shape #3
T #1
_output_shapes #0
Tcrops #3
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nTblock_shape #3
_output_shapes #0
Tpaddings #3
T #1
BatchToSpaceND not supported yet !
nTblock_shape #3
T #1
_output_shapes #0
Tcrops #3
FusedBatchNorm not supported yet !
nT #1
is_training #0
epsilon #0
_output_shapes #0
data_format #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
nT #1
_output_shapes #0
SpaceToBatchND not supported yet !
nTblock_shape #3
_output_shapes #0
Tpaddings #3
T #1
BatchToSpaceND not supported yet !
nTblock_shape #3
T #1
_output_shapes #0
Tcrops #3
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
nT #1
_output_shapes #0
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nT #1
Tblock_shape #3
_output_shapes #0
Tpaddings #3
BatchToSpaceND not supported yet !
nTblock_shape #3
T #1
_output_shapes #0
Tcrops #3
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nT #1
Tblock_shape #3
_output_shapes #0
Tpaddings #3
BatchToSpaceND not supported yet !
nTcrops #3
_output_shapes #0
Tblock_shape #3
T #1
FusedBatchNorm not supported yet !
nis_training #0
data_format #0
T #1
_output_shapes #0
epsilon #0
Relu6 not supported yet !
n_output_shapes #0
T #1
Relu6 not supported yet !
nT #1
_output_shapes #0
SpaceToBatchND not supported yet !
nTblock_shape #3
_output_shapes #0
Tpaddings #3
T #1
BatchToSpaceND not supported yet !
nTcrops #3
_output_shapes #0
Tblock_shape #3
T #1
FusedBatchNorm not supported yet !
nT #1
is_training #0
epsilon #0
_output_shapes #0
data_format #0
Relu6 not supported yet !
nT #1
_output_shapes #0
Relu6 not supported yet !
n_output_shapes #0
T #1
SpaceToBatchND not supported yet !
nT #1
Tblock_shape #3
_output_shapes #0
Tpaddings #3
BatchToSpaceND not supported yet !
nTcrops #3
_output_shapes #0
Tblock_shape #3
T #1
FusedBatchNorm not supported yet !
nT #1
epsilon #0
_output_shapes #0
is_training #0
data_format #0
Relu6 not supported yet !
n_output_shapes #0
T #1
ResizeBilinear not supported yet !
nT #1
align_corners #0
_output_shapes #0
ResizeBilinear not supported yet !
nT #1
align_corners #0
_output_shapes #0

**Comment by nihui** [comment] 2018-12-18 03:12
duplicate of https://github.com/Tencent/ncnn/issues/5

**Closed by nihui** 2018-12-18 03:12 UTC
Labels: tensorflow do not like ncnn
