### ISSUE TITLE
使用vulkan推理vkDestroyDevice时崩溃

### ISSUE THREAD

**Issue by nicheng0019** [Tencent/ncnn#4329] opened 2022-11-03 08:40 UTC
## error log | 日志或报错信息 | ログ
0x0000000000000000 处(位于 nanodet.exe 中)引发的异常: 0xC0000005: 执行位置 0x0000000000000000 时发生访问冲突。

## context | 编译/运行环境 | バックグラウンド
win10，使用visual studio 2019编译，编译选项设置为
-DNCNN_VULKAN=ON -DNCNN_BUILD_EXAMPLES=ON -DNCNN_BUILD_BENCHMARK=ON -DNCNN_BUILD_TOOLS=ON -DNCNN_BUILD_TESTS=ON  -DNCNN_SIMPLEOCV=ON -DNCNN_SHARED_LIB=ON ..

## how to reproduce | 复现步骤 | 再現方法
1.运行examples里的nanodet，程序退出时崩溃，打断点崩溃的位置在
`VulkanDevice::~VulkanDevice()
{
    d->destroy_utility_operator();

    d->destroy_dummy_buffer_image();

    if (d->texelfetch_sampler)
    {
        vkDestroySampler(d->device, d->texelfetch_sampler, 0);
    }

    for (size_t i = 0; i < d->blob_allocators.size(); i++)
    {
        delete d->blob_allocators[i];
    }
    d->blob_allocators.clear();
    for (size_t i = 0; i < d->staging_allocators.size(); i++)
    {
        delete d->staging_allocators[i];
    }
    d->staging_allocators.clear();

    delete d->pipeline_cache;

    vkDestroyDevice(d->device, 0);

    delete d;
}`

中的vkDestroyDevice(d->device, 0);这一行：

## more | 其他 | その他
ncnn编译成静态库不崩溃，编译成动态库会崩溃；

**Comment by nihui** [comment] 2023-12-19 09:33
https://github.com/Tencent/ncnn/pull/5234

**Comment by nihui** [comment] 2023-12-20 03:33
fixed in https://github.com/Tencent/ncnn/commit/ded0b78bb2926d3fd116c94d988c8e3d836d191a

**Closed by nihui** 2023-12-20 03:33 UTC

**Comment by hhxdestiny** [comment] 2024-03-14 11:34
@nihui Hello, This issue seems to be reproducible in the latest version!
