### ISSUE TITLE
tag 20191113 version get the strange result for optimal mnas model

### ISSUE THREAD

**Issue by IvyGongoogle** [Tencent/ncnn#1557] opened 2020-02-26 04:59 UTC
Hello, when I use `tag 20191113` ncnn to extract `prob` from my optimal model [mnas.zip](https://github.com/Tencent/ncnn/files/4253446/mnas.zip) with different images and different size, it always output the `0.000034` value for top3 and the blob values within the inference process are always 0.  But when I use commit `5dcd566` ncnn, it works.  This is so strange.

Can you give some advises?
Looking for your reply...

**Comment by nihui** [comment] 2020-02-26 08:43
If the issue is resolved in the latest release, why don't you use it ?

**Comment by IvyGongoogle** [comment] 2020-03-06 12:28
@nihui  thanks for your reply. because I develop a lot of codes using old version. So it is big work for replace the latest release. 

This issue has been solved for my mistake. Close it now~

**Closed** 2020-03-06 12:28 UTC
